apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop-roche
  namespace: argocd
spec:
  sourceRepos:
    - '*'

  destinations:
    - server: '*'
      namespace: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'