apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: ${WORKSHOP_NAME}
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - stage: dev
          - stage: test
          - stage: prod

  template:
    metadata:
      name: ${WORKSHOP_NAME}-nginx-{{stage}}

      annotations:
        kargo.akuity.io/authorized-stage: ${WORKSHOP_NAME}:{{stage}}

    spec:
      project: akuity-workshop

      source:
        repoURL: ${GITOPS_REPO_URL}
        targetRevision: stage/{{stage}}
        path: .

      destination:
        name: ${ARGOCD_DESTINATION}
        namespace: ${WORKSHOP_NAME}-{{stage}}

      syncPolicy:
        syncOptions:
          - CreateNamespace=true