apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kargo-akuity-workshop
  namespace: argocd

spec:
  project: akuity-workshop

  source:
    repoURL: ${GITOPS_REPO_URL}
    path: kargo

  destination:
    name: ${ARGOCD_DESTINATION}
    namespace: akuity-workshop

  syncPolicy:
    syncOptions:
      - CreateNamespace=true